"""trade and tradeLeg tables

Revision ID: 81c48ef2c4c3
Revises: d82f3afa725a
Create Date: 2020-09-23 16:10:39.424113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c48ef2c4c3'
down_revision = 'd82f3afa725a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=4), nullable=True),
    sa.Column('playid', sa.String(length=10), nullable=True),
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=6), nullable=True),
    sa.Column('no_contracts', sa.Integer(), nullable=True),
    sa.Column('no_legs', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('dailypnl', sa.Float(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('open_premium', sa.Float(), nullable=True),
    sa.Column('open_underlying', sa.Float(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('close_premium', sa.Float(), nullable=True),
    sa.Column('close_underlying', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_open_date'), 'trade', ['open_date'], unique=False)
    op.create_index(op.f('ix_trade_ticker'), 'trade', ['ticker'], unique=False)
    op.create_table('trade_leg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opened', sa.String(length=6), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.String(length=4), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_leg')
    op.drop_index(op.f('ix_trade_ticker'), table_name='trade')
    op.drop_index(op.f('ix_trade_open_date'), table_name='trade')
    op.drop_table('trade')
    # ### end Alembic commands ###
